"use client";
import { useEffect,useState } from "react";
type Section="inicio"|"servicos"|"projetos"|"maquinas"|"atalhos"|"configuracoes";
type LinkItem={id:number;name:string;url:string;category:string};
type Metrics={online:boolean;hostname:string;username:string;os:string;cpu:{percent:number;name:string;cores:number;threads:number};ram:{percent:number;usedGb:number;totalGb:number};disk:{percent:number;usedGb:number;totalGb:number;freeGb:number};gpu:{name:string;vramGb:number;driver:string}[];network:{adapters:{name:string;description:string;speed:string;mac:string}[];ipv4:string[]};processes:{name:string;pid:number;ramMb:number;cpuSeconds:number}[];services:{name:string;displayName:string;status:string}[];uptimeHours:number;timestamp:string;agentVersion:string};
const LINKS_KEY="maike-hub:tech-links",AGENT_URL="http://127.0.0.1:43123/status";
const initialLinks:LinkItem[]=[{id:1,name:"GitHub",url:"https://github.com",category:"Dev"},{id:2,name:"Vercel",url:"https://vercel.com",category:"Deploy"},{id:3,name:"Registro.br",url:"https://registro.br",category:"Domínios"},{id:4,name:"Tiflux",url:"https://tiflux.com",category:"Trabalho"}];
function NavButton({id,icon,label,section,onSelect}:{id:Section;icon:string;label:string;section:Section;onSelect:(id:Section)=>void}){return <button className={`navItem ${section===id?"active":""}`} onClick={()=>onSelect(id)}>{icon} <span>{label}</span></button>}
export default function Home(){
 const[section,setSection]=useState<Section>("inicio"),[links,setLinks]=useState<LinkItem[]>(initialLinks),[name,setName]=useState(""),[url,setUrl]=useState(""),[hydrated,setHydrated]=useState(false),[metrics,setMetrics]=useState<Metrics|null>(null),[agentChecked,setAgentChecked]=useState(false);
 useEffect(()=>{try{const s=localStorage.getItem(LINKS_KEY);if(s)setLinks(JSON.parse(s))}finally{setHydrated(true)}},[]);useEffect(()=>{if(hydrated)localStorage.setItem(LINKS_KEY,JSON.stringify(links))},[links,hydrated]);
 useEffect(()=>{let alive=true;async function poll(){try{const r=await fetch(AGENT_URL,{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();if(alive)setMetrics(d)}catch{if(alive)setMetrics(null)}finally{if(alive)setAgentChecked(true)}}poll();const t=setInterval(poll,3000);return()=>{alive=false;clearInterval(t)}},[]);
 function addLink(){const n=name.trim();let u=url.trim();if(!n||!u)return;if(!/^https?:\/\//i.test(u))u=`https://${u}`;setLinks(c=>[...c,{id:Date.now(),name:n,url:u,category:"Personalizado"}]);setName("");setUrl("")}
 const badge=metrics?<span className="badge ok">AGENTE ONLINE</span>:<span className="badge warn">AGENTE OFF</span>;
 const services=<div className="serviceGrid"><article className="serviceCard"><div className="serviceTop"><strong>Maike Hub</strong><span className="badge ok">ONLINE</span></div><p>hub.maikedev.com.br</p><small>Vercel</small></article><article className="serviceCard"><div className="serviceTop"><strong>Domínio</strong><span className="badge neutral">DNS</span></div><p>maikedev.com.br</p><small>Registro.br</small></article><article className="serviceCard"><div className="serviceTop"><strong>GitHub</strong><span className="badge ok">CONECTADO</span></div><p>awmaike/maike-hub</p><small>Deploy automático</small></article><article className="serviceCard"><div className="serviceTop"><strong>Windows</strong>{badge}</div><p>{metrics?.hostname||"Agente local"}</p><small>{metrics?`Agent v${metrics.agentVersion}`:"Aguardando agente"}</small></article></div>;
 const machine=metrics?<><article className="panel"><div className="panelHeader"><div><p className="eyebrow">TELEMETRIA AO VIVO</p><h2>{metrics.hostname}</h2></div>{badge}</div><div className="metricCards"><MetricCard label="CPU" value={`${metrics.cpu.percent}%`} detail={`${metrics.cpu.cores} cores · ${metrics.cpu.threads} threads`} percent={metrics.cpu.percent}/><MetricCard label="RAM" value={`${metrics.ram.percent}%`} detail={`${metrics.ram.usedGb} / ${metrics.ram.totalGb} GB`} percent={metrics.ram.percent}/><MetricCard label="Disco C:" value={`${metrics.disk.percent}%`} detail={`${metrics.disk.freeGb} GB livres`} percent={metrics.disk.percent}/><MetricCard label="Uptime" value={`${metrics.uptimeHours}h`} detail={metrics.os}/></div><div className="hardwareInfo"><p><b>CPU:</b> {metrics.cpu.name}</p><p><b>GPU:</b> {metrics.gpu?.map(g=>`${g.name}${g.vramGb?` (${g.vramGb} GB)`:""}`).join(" · ")||"Não detectada"}</p><p><b>IPv4:</b> {metrics.network?.ipv4?.join(" · ")||"Não detectado"}</p><p><b>Rede:</b> {metrics.network?.adapters?.map(a=>`${a.name} ${a.speed}`).join(" · ")||"Não detectada"}</p></div></article><article className="panel"><div className="panelHeader"><div><p className="eyebrow">PROCESSOS</p><h2>Maior uso de memória</h2></div><span className="badge neutral">TOP 8</span></div><div className="processTable"><div className="processRow head"><span>Processo</span><span>PID</span><span>RAM</span><span>CPU total</span></div>{metrics.processes?.map(p=><div className="processRow" key={`${p.pid}-${p.name}`}><strong>{p.name}</strong><span>{p.pid}</span><span>{p.ramMb} MB</span><span>{p.cpuSeconds}s</span></div>)}</div></article><article className="panel"><div className="panelHeader"><div><p className="eyebrow">SERVIÇOS</p><h2>Serviços Windows ativos</h2></div><span className="badge ok">RUNNING</span></div><div className="serviceList">{metrics.services?.slice(0,12).map(s=><div key={s.name}><span className="statusDot"/><div><strong>{s.displayName}</strong><small>{s.name}</small></div></div>)}</div></article></>:<article className="panel"><h2>{agentChecked?"Agente não detectado":"Procurando agente..."}</h2><p className="muted">O agente precisa estar rodando neste Windows.</p></article>;
 const shortcuts=<><div className="linkComposer"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do atalho"/><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addLink()} placeholder="https://..."/><button onClick={addLink}>Adicionar</button></div><div className="techLinks">{links.map(l=><a key={l.id} href={l.url} target="_blank" rel="noreferrer"><span>{l.category}</span><strong>{l.name}</strong><small>{l.url.replace(/^https?:\/\//,"")}</small></a>)}</div></>;
 let content;if(section==="servicos")content=<><Header eyebrow="INFRAESTRUTURA" title="Serviços" subtitle="Sites, domínios, deploys e disponibilidade."/>{services}</>;else if(section==="projetos")content=<><Header eyebrow="DESENVOLVIMENTO" title="Projetos" subtitle="Código, builds e deploys."/><div className="serviceGrid"><article className="serviceCard"><strong>Maike Hub</strong><p>Next.js · GitHub · Vercel</p></article><article className="serviceCard"><strong>Agente Windows</strong><p>PowerShell · localhost · v1.1</p></article></div></>;else if(section==="maquinas")content=<><Header eyebrow="HARDWARE" title="Máquinas" subtitle="Um mini Gerenciador de Tarefas dentro do Hub."/><div className="stack">{machine}</div></>;else if(section==="atalhos")content=<><Header eyebrow="FERRAMENTAS" title="Atalhos" subtitle="Sua central de acessos técnicos."/>{shortcuts}</>;else if(section==="configuracoes")content=<><Header eyebrow="SISTEMA" title="Configurações" subtitle="Integrações e próximos passos."/><article className="panel"><div className="roadmap"><p>01 — Telemetria Windows avançada ✅</p><p>02 — Monitoramento real de sites</p><p>03 — GitHub: commits e repositórios</p><p>04 — Vercel: deploys e builds</p></div></article></>;else content=<><Header eyebrow="CENTRAL TÉCNICA" title="Maike Hub" subtitle="Infraestrutura, desenvolvimento e máquinas."/><section className="stats"><article className="statCard"><span>Máquina</span><strong>{metrics?"Online":"Offline"}</strong><small>{metrics?.hostname||"aguardando"}</small></article><article className="statCard"><span>CPU</span><strong>{metrics?`${metrics.cpu.percent}%`:"—"}</strong><small>{metrics?`${metrics.cpu.cores} cores`:"sem agente"}</small></article><article className="statCard"><span>RAM</span><strong>{metrics?`${metrics.ram.percent}%`:"—"}</strong><small>{metrics?`${metrics.ram.usedGb}/${metrics.ram.totalGb} GB`:"sem agente"}</small></article><article className="statCard"><span>Disco</span><strong>{metrics?`${metrics.disk.percent}%`:"—"}</strong><small>{metrics?`${metrics.disk.freeGb} GB livres`:"sem agente"}</small></article></section><section className="dashboardGrid"><article className="panel wide"><div className="panelHeader"><div><p className="eyebrow">INFRA</p><h2>Serviços</h2></div></div>{services}</article><article className="panel"><div className="panelHeader"><h2>Meu PC</h2>{badge}</div>{metrics?<><p className="muted">{metrics.cpu.name}</p><button className="primaryButton" onClick={()=>setSection("maquinas")}>Abrir monitor</button></>:<p className="muted">Aguardando agente.</p>}</article></section></>;
 return <main className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark">M</div><div><strong>Maike Hub</strong><span>Tech Control</span></div></div><nav><NavButton id="inicio" icon="⌂" label="Visão geral" section={section} onSelect={setSection}/><NavButton id="servicos" icon="◉" label="Serviços" section={section} onSelect={setSection}/><NavButton id="projetos" icon="⌘" label="Projetos" section={section} onSelect={setSection}/><NavButton id="maquinas" icon="▣" label="Máquinas" section={section} onSelect={setSection}/><NavButton id="atalhos" icon="↗" label="Atalhos" section={section} onSelect={setSection}/><NavButton id="configuracoes" icon="⚙" label="Configurações" section={section} onSelect={setSection}/></nav><div className="sidebarBottom"><div className="statusDot"/><span>Hub online</span></div></aside><section className="content">{content}</section></main>}
function Header({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{subtitle}</p></div><div className="avatar">M</div></header>}
function MetricCard({label,value,detail,percent}:{label:string;value:string;detail:string;percent?:number}){return <div className="metricCard"><span>{label}</span><strong>{value}</strong><small>{detail}</small>{typeof percent==="number"&&<div className="meter"><i style={{width:`${Math.min(100,Math.max(0,percent))}%`}}/></div>}</div>}
